[package]
name = "clitest-integration"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
clitest-lib.workspace = true
pretty_assertions.workspace = true
termcolor.workspace = true
dunce.workspace = true

[[test]]
name = "integration_tests"
harness = false
